{{- if and (not .Values.existingSecretName) (gt (len .Values.secretEnv) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
