namespace: apps

image:
  repository: myapp         # the local/tag name from your CI build (will be overridden in deploy job)
  tag: "latest"             # CI will set this to the short/full SHA
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

replicaCount: 1  # HPA will control this when enabled

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

probes:
  liveness:
    path: /failcheck
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: true
  name: ""  # if set, use this name; else use fullname template

# Non-sensitive env vars go here (ConfigMap)
env:
  APP_NAME: "flask-sample"

# Sensitive env vars → rendered into a Secret
secretEnv:
  # Example:
  # DB_PASSWORD: "supersecret"

# You can point to an existing secret instead of creating one
existingSecretName: ""

networkPolicy:
  enabled: true
  # Only allow traffic from namespaces with this label OR pods with this label
  allowFromNamespaces:
    - key: "kubernetes.io/metadata.name"
      value: "kube-system"
    - key: "name"
      value: "apps"         # allows same namespace if you label the ns name=apps
  allowFromPods:
    - key: "app.kubernetes.io/name"
      value: "nginx-ingress"  # example; adjust or remove

podAnnotations: {}
labels: {}
