name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Python SAST scanning
      - name: Run Bandit (SAST for Python)
        uses: py-actions/py-bandit@v1
        with:
          path: app/

      # Dependency scanning
      - name: Run pip-audit (dependency vulnerability scan)
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

      test:
    name: Run unit tests (pytest)
    needs: [security-scan]           # run after security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # dev deps (pytest, coverage) if not already in requirements.txt
          pip install pytest pytest-cov

      # If your tests live in app/tests; adjust if different
      - name: Run pytest with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing
        env:
          PYTHONPATH: .

      # Save JUnit XML (optional but helpful for PRs)
      - name: Generate JUnit report
        if: always()
        run: |
          pytest -q --junitxml=pytest-results.xml || true

      - name: Upload test report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml
