name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit (SAST for Python)
        uses: py-actions/py-bandit@v1
        with:
          path: app/

      - name: Run pip-audit (dependency vulnerability scan)
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt

  test:
    name: Run unit tests (pytest)
    needs: [security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run pytest with coverage
        env:
          PYTHONPATH: .
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing

      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml
