name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bandit and pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

      - name: Run Bandit (SAST for Python)
        run: bandit -r app/ -ll

      - name: Run pip-audit (dependency vulnerability scan)
        run: pip-audit -r requirements.txt
